### ISSUE TITLE
Module names are unnecessarily limited

### ISSUE THREAD

**Issue by Fripe070** [ThatOtherAndrew/ThatOtherBot#10]
### Describe the bug
Modules can’t have names containing certain symbols, even though there shouldn’t be anything preventing it.

### To Reproduce
Steps to reproduce the behaviour:
1. Make a module with the name `🗿`
2. Be disappointed

### Expected behaviour
A module with the name `🗿` would be created, but instead, an error is thrown.

**Comment by Sophon96** [comment]
This actually raises a proper concern—what characters **should** be allowed in `name`? Anything but whitespace?

**Comment by m31-galaxy** [comment]
Won't fix, emojis are unfortunately not valid attribute identifiers in Python. Go be not angry, just disappointed, at Python instead

![Screenshot_20221230-230821.png](https://user-images.githubusercontent.com/26030336/210117286-8b759b60-892e-476c-bcef-38cdad55024f.png)

**Comment by m31-galaxy** [comment]
> This actually raises a proper concern—what characters **should** be allowed in `name`? Anything but whitespace?

At the moment, the constraint is 1-32 characters which are alphanumeric, underscores or hyphens.

**Comment by m31-galaxy** [comment]
I am also considering enforcing that the name does not start with an underscore, as that is understood to mean a private attribute in Python. However that may be unnecessary, and I can see legitimate use cases for wanting modules to be faux-private, e.g. a debugger module.
