### ISSUE TITLE
Allow specifying module guild permissions in manifest

### ISSUE THREAD

**Issue by Fripe070** [ThatOtherAndrew/ThatOtherBot#16]
### Problem
Some modules may require certain permissions such as `delete_messages` in order to function, which the user needs to be informed about in some way, preferably not by the module spitting out an error.

### Possible solution
Allow specifying the required permissions in the module manifest, either as a list of the required permissions names, or as the permission integers used by discord’s api. 
Then prompt the user with a warning about the permissions needed when loading and/or installing a module.

### Alternative solution
Allow the module developer to specify the required permissions for each command (or other function/method needing some permission) individually, in the form of a function decorator. This approach would however be more complex, and I can’t personally think of a good way of informing the user about the needed permissions.

**Comment by m31-galaxy** [comment]
I quite like the idea of declaring permissions in the manifest - a bit like browser extensions or mobile apps - which can then be shown during module installation. This would tie in quite nicely with #13 as well, which would then depend on this issue.

**Comment by m31-galaxy** [comment]
Implemented! The manifest now has a `permissions` field which is an array of strings, e.g. `permissions = ["manage_guild", "view_audit_log"]`.
