### ISSUE TITLE
Add system to require intents based off of the need of the currently activated modules

### ISSUE THREAD

**Issue by alf1e** [ThatOtherAndrew/ThatOtherBot#17]
### Is your feature request related to a problem/inconvenience? Please describe.
Related to the fact that intents is set to all

### Describe the solution you'd like
I think a good solution would be that a module puts the required intents in its manifest and then only those intents get loaded by the bot

**Comment by m31-galaxy** [comment]
Intents must be declared upon the bot's startup, before modules are loaded. To accomplish this would require a preflight-like parsing of all module schemas, which isn't optimal but is possible. Does having all privileged intents being enabled pose an issue to you?

**Comment by alf1e** [comment]
I feel like it would foresee an issue for if any running instance of the bot passes 100 members having to go through the verification for all the intents. Plus it is good practice to only have an intent if you need it.

**Comment by m31-galaxy** [comment]
While I understand that the principle of least privilege is good practice, here it gets in the way of functionality. What do you propose is done if a bot starts up without requiring any privileged intents, and then enables a module which does require such intents? Should a restart of the bot be forced?

**Comment by alf1e** [comment]
It could run a quick parse of the manifest before initialising the bot

**Comment by m31-galaxy** [comment]
That is the "preflight" I described earlier, however that still doesn't solve the issue of dynamically enabled modules while the bot is already running.
