### ISSUE TITLE
GH actions ruff and local ruff are different versions

### ISSUE THREAD

**Issue by Fripe070** [ThatOtherAndrew/ThatOtherBot#192]
### Checklist

- [X] I have been able to successfully and reliably reproduce the issue.
- [X] I confirm this issue is present as of the latest commit on the `main` branch.
- [X] I have searched for a similar issue in this repository and didn't find anything relevant.

### Description
The local ruff version, as set in dev_requirements.txt is pinned and handled by dependabot. The ruff version in the lint github action is always set to the latest (see [ChartBoost/ruff-action](https://github.com/ChartBoost/ruff-action)). This results in the action throwing an error when local testing succeded.

### Possible fix
We can either unpin ruff in our dev requirements, or pin the version in the github action. I am not sure if dependabot will be smart enough to automatically update the github actions variable though.

**Comment by m31-galaxy** [comment]
This is a tricky dilemma, actually. Updating the environment varable seems like an incredible pain though, so as bad practice as it is, I think we should just let Ruff take the wheel with the latest version.

**Comment by Fripe070** [comment]
This will be implemented in #194 and it will be set to not being WIP

**Comment by Fripe070** [comment]
It has been done
