### ISSUE TITLE
Auto update fails if ahead of origin

### ISSUE THREAD

**Issue by Fripe070** [ThatOtherAndrew/ThatOtherBot#221]
### Checklist
- [x] I have been able to successfully and reliably reproduce the issue.
- [x] I confirm this issue is present as of the latest commit on the `main` branch.
- [x] I have searched for a similar issue in this repository and didn't find anything relevant.

### Description
If a module is ahead of origin then the auto_update core module will believe it is out of date

### Reproduction

1. Clone a module from GitHub, for example [OwnerUtils](https://github.com/Breadcord-Toasts/OwnerUtils)
2. Commit something in the OwnerUtils git repo, but don't push
3. Run the bot

### Expected behavior
The auto update module should treat the module as if it is up to date with origin

**Comment by m31-galaxy** [comment]
What would be the best way to handle this edge case?

**Comment by Fripe070** [comment]
Not doing this to check if the local branch is behind.
https://github.com/Breadcord/Breadcord/blob/main/breadcord/core_modules/auto_update/__init__.py#L82-L86

**Comment by m31-galaxy** [comment]
Is the plan to overwrite local with remote then? Or attempt a merge/rebase and have the update safely fail on merge conflict?

**Comment by Fripe070** [comment]
> Is the plan to overwrite local with remote then? Or attempt a merge/rebase and have the update safely fail on merge conflict?

To have it fail.
