### ISSUE TITLE
Settings.toml file not automatically created

### ISSUE THREAD

**Issue by PeeblyWeeb** [ThatOtherAndrew/ThatOtherBot#4]
### Describe the bug
Bot doesn't automatically create config/settings.toml and errors instead

### To Reproduce
Steps to reproduce the behaviour:
1. clone repo
2. run bot

### Expected behavior
my config/settings.toml file to exist

### Additional context

`FileNotFoundError: [Errno 2] No such file or directory: 'config/settings.toml'`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "A:\code\python\ThatOtherBot\bot\__main__.py", line 3, in <module>
    bot = Bot()
          ^^^^^
  File "A:\code\python\ThatOtherBot\bot\bot.py", line 16, in __init__
    self.load_settings()
  File "A:\code\python\ThatOtherBot\bot\bot.py", line 36, in load_settings
    loaded_settings = config.load_settings('config/settings.toml')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\code\python\ThatOtherBot\bot\config.py", line 161, in load_settings
    return TOMLFile(file_path).read().unwrap()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\code\python\ThatOtherBot\venv\Lib\site-packages\tomlkit\toml_file.py", line 31, in read
    with open(self._path, encoding="utf-8", newline="") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by m31-galaxy** [comment]
@PeeblyWeeb I'm testing out a fix for this issue - thoughts on the user-friendliness of this?



![Image](https://user-images.githubusercontent.com/26030336/209718456-026f46d0-32a8-4bba-ba0a-ec78499afe55.png)

**Comment by PeeblyWeeb** [comment]
looks good to me! 10/10

**Comment by alf1e** [comment]
> @PeeblyWeeb I'm testing out a fix for this issue - thoughts on the user-friendliness of this?
> 
> ![Image](https://user-images.githubusercontent.com/26030336/209718456-026f46d0-32a8-4bba-ba0a-ec78499afe55.png)

Personally, The warning should be escalated because the bot can't start without it.

**Comment by m31-galaxy** [comment]
> Personally, The warning should be escalated because the bot can't start without it.
@alf1e I disagree - because this is, well, a warning to the user. It's not an error, because everything's working as intended - an error will only be raised if the user then tries to start the bot without a valid token.

**Comment by PeeblyWeeb** [comment]
facts, I think its perfect. alfie ur wrong hehehehaw
