### ISSUE TITLE
Add command line argument for specifying more specific paths

### ISSUE THREAD

**Issue by Fripe070** [ThatOtherAndrew/ThatOtherBot#61]
### Checklist

- [x] I am willing to follow this issue and provide additional information and feedback.
- [x] I have searched for a similar feature in this repository and didn't find anything relevant.
- [x] I am willing to provide specific implementation or solution examples to aid design and development.

### Problem
Previously, you were able to specify a module directory in the startup args, now you need to specify the entire data directory, allowing for much less freedom.

### Solution
I would like to see a module directory argument added back, along with arguments for specifying the log directory, storage directory & settings file.

**Comment by m31-galaxy** [comment]
I moved all user/instance data into a single directory by default as this makes it easy to manipulate as a single "unit", and therefore can be mounted into Docker containers easily. More granular control could indeed be useful for a local dev environment though, and this should be easy to implement as all the paths are properties of `breadcord.bot.Bot`.

**Comment by m31-galaxy** [comment]
https://github.com/Breadcord/Breadcord/commit/65cc2050cd5f1981461d4a3fc83b12da225af2a2 is a step towards the right direction here.
