### ISSUE TITLE
Rename the project to a more fitting name

### ISSUE THREAD

**Issue by m31-galaxy** [ThatOtherAndrew/ThatOtherBot#7]
Currently the options are, in order of my preference:
1. Breadcord (Portmanteau of Breadboard and Discord, suggested by @PeeblyWeeb)
2. Modulus (Reference to the mathematical term and the modularity of the bot, suggested by @alf1e)

**Comment by alf1e** [comment]
Modulus

**Comment by m31-galaxy** [comment]
Renamed to Breadcord.
