### ISSUE TITLE
Module names are case-sensitive 

### ISSUE THREAD

**Issue by PeeblyWeeb** [ThatOtherAndrew/ThatOtherBot#8]
![pycharm64_Ct5FiR4xaK](https://user-images.githubusercontent.com/74932007/210115076-8a9d38d2-36f2-4a57-aa31-a11eef8bf1ee.png)

**Comment by m31-galaxy** [comment]
Works as intended - currently module names use strict equality checks to prevent complications with conflicts, e.g. two modules with directory names which are different only in capitalisation. This also reduces the chance of two independently developed modules having a conflicting name.

If you believe that despite this, module names should be case-insensitive, then that can be discussed further.

**Comment by PeeblyWeeb** [comment]
I find it kind of confusing seeing the same module name with different capitalization. In my own opinion I think modules should be strictly compared by their manifest.toml and somehow differentiated in the settings.toml file. 

Perhaps you could use the authors list to do something like this:
![image](https://user-images.githubusercontent.com/74932007/210115724-486ec749-904c-4afa-a079-db7aa517c0f0.png)

**Comment by m31-galaxy** [comment]
That would be even more confusing - for example, what authors do I use? What if the authors change? Should the author suffix be required for all modules, in which case that's ugly and verbose, or should it only be required for conflicting modules? If the latter, then that causes other issues down the line, such as if a new conflicting module is installed - should the module ID be renamed in-place? What about other modules which could depend on this ID?

Personally, I really don't like the idea of dynamic names or IDs like that - fundamentally an ID used for referencing a module should change as little as possible. If you do not want case sensitivity, then the only viable route I see is to cast all names to lowercase.

**Comment by PeeblyWeeb** [comment]
That's honestly a lot I didn't think about, but that's also just an idea. There's got to be a better way to do it right?

**Comment by m31-galaxy** [comment]
If you have any ideas then feel free to suggest them. I'm tired of keeping up this formal facade though so I'll discuss this on Discord from here lmao
