### ISSUE TITLE
Case-insensitive prefixes

### ISSUE THREAD

**Issue by Fripe070** [ThatOtherAndrew/ThatOtherBot#97]
### Checklist

- [X] I am willing to follow this issue and provide additional information and feedback.
- [X] I have searched for a similar feature in this repository and didn't find anything relevant.
- [X] I am willing to provide specific implementation or solution examples to aid design and development.

### Problem
Command prefix matching is case-sensitive. This is an issue if a bot owner uses a prefix containing letters with an uppercase and lowercase form. When a user then tries to use a version of the prefix with different capitalisation than what is specified in settings, the bot will not respond.

### Solution
Ignore capitalisation when matching the prefix, for example through passing the incoming message and the prefix through `str.lower()` before matching.

**Comment by m31-galaxy** [comment]
As discussed on Discord, I'm handing this issue off to you (because I'm lazy :trollface:) - please update [the project](https://github.com/orgs/Breadcord/projects/1) accordingly if/when you work on it :>
